--[[
    EC Admin Ultimate - Configuration Loader
    This file automatically loads the correct config based on host mode detection
    
    DO NOT EDIT THIS FILE DIRECTLY
    Edit host.config.lua (for host mode) or customer.config.lua (for customer mode) instead
    
    This file is dynamically loaded by shared/config-loader.lua which sets _EC_CONFIG_SOURCE
]]

-- Load the appropriate config file
local configSource = _EC_CONFIG_SOURCE or 'customer.config.lua'
local configMode = _EC_CONFIG_MODE or 'CUSTOMER'

-- Load and execute the config file
-- Config files are in root directory
local resourceName = GetCurrentResourceName()
local configContent = nil

-- Try multiple ways to load the config file
-- Method 1: Direct path
configContent = LoadResourceFile(resourceName, configSource)

-- Method 2: Try with resource name as string
if not configContent then
    configContent = LoadResourceFile(GetCurrentResourceName(), configSource)
end

-- Method 3: Try reading the file directly (if it's a server-side script)
if not configContent and IsDuplicityVersion() then
    -- On server, we can try to read the file directly
    local file = io.open(GetResourcePath(resourceName) .. '/' .. configSource, 'r')
    if file then
        configContent = file:read('*all')
        file:close()
    end
end

if not configContent then
    print("^3[Config]^7 WARNING: Could not load " .. configSource .. " from resource " .. resourceName .. "^0")
    -- Only try to get resource path on server-side (GetResourcePath is server-only)
    if IsDuplicityVersion() and GetResourcePath then
        local success, resourcePath = pcall(function() return GetResourcePath(resourceName) end)
        if success and resourcePath then
            print("^3[Config]^7 Resource path: " .. tostring(resourcePath) .. "^0")
        end
    end
    print("^3[Config]^7 This is normal if the config file doesn't exist yet. Using empty config.^0")
end

if not configContent then
    print("^1[Config] ERROR: Could not load " .. configSource .. "^0")
    print("^1[Config] ERROR: Falling back to empty config^0")
    Config = Config or {}
    return Config
end

-- Execute the config file content
local configFunc, err = load(configContent, configSource)

if not configFunc then
    print("^1[Config] ERROR: Failed to parse " .. configSource .. ": " .. tostring(err) .. "^0")
    Config = Config or {}
    return Config
end

-- Run the config function to get Config table
local success, result = pcall(configFunc)

if not success then
    print("^1[Config] ERROR: Failed to execute " .. configSource .. ": " .. tostring(result) .. "^0")
    Config = Config or {}
    return Config
end

-- If config file returns Config, use it; otherwise Config should be set globally
if result and type(result) == 'table' then
    Config = result
elseif not Config then
    Config = {}
end

print("^2[Config]^7 Successfully loaded " .. configMode .. " configuration from " .. configSource .. "^0")

return Config
