--[[
    EC Admin Ultimate - Configuration Loader
    This file automatically loads the correct config based on host mode detection
    
    DO NOT EDIT THIS FILE DIRECTLY
    Edit host.config.lua (for host mode) or customer.config.lua (for customer mode) instead
    
    This file is dynamically loaded by shared/config-loader.lua which sets _EC_CONFIG_SOURCE
]]

-- Load the appropriate config file
local configSource = _EC_CONFIG_SOURCE or 'customer.config.lua'
local configMode = _EC_CONFIG_MODE or 'CUSTOMER'

-- Load and execute the config file
local configContent = LoadResourceFile(GetCurrentResourceName(), configSource)

if not configContent then
    print("^1[Config] ERROR: Could not load " .. configSource .. "^0")
    print("^1[Config] ERROR: Falling back to empty config^0")
    Config = Config or {}
    return Config
end

-- Execute the config file content
local configFunc, err = load(configContent, configSource)

if not configFunc then
    print("^1[Config] ERROR: Failed to parse " .. configSource .. ": " .. tostring(err) .. "^0")
    Config = Config or {}
    return Config
end

-- Run the config function to get Config table
local success, result = pcall(configFunc)

if not success then
    print("^1[Config] ERROR: Failed to execute " .. configSource .. ": " .. tostring(result) .. "^0")
    Config = Config or {}
    return Config
end

-- If config file returns Config, use it; otherwise Config should be set globally
if result and type(result) == 'table' then
    Config = result
elseif not Config then
    Config = {}
end

print("^2[Config]^7 Successfully loaded " .. configMode .. " configuration from " .. configSource .. "^0")

return Config
