// EC Admin Ultimate - Setup API Routes
// Handles setup wizard API endpoints

const express = require('express');
const router = express.Router();
const fs = require('fs').promises;
const path = require('path');

// ============================================================================
// ENVIRONMENT CHECK
// ============================================================================

router.get('/status', async (req, res) => {
  try {
    // Check if config.lua exists
    const configPath = path.join(__dirname, '../../../config.lua');
    let configExists = false;
    
    try {
      await fs.access(configPath);
      configExists = true;
    } catch {
      configExists = false;
    }
    
    // Return environment status
    res.json({
      nodeVersion: process.version,
      platform: process.platform,
      configExists: configExists,
      setupComplete: configExists
    });
  } catch (error) {
    console.error('Error getting setup status:', error);
    res.status(500).json({ error: 'Failed to get setup status' });
  }
});

// ============================================================================
// TEST DATABASE CONNECTION
// ============================================================================

router.post('/test-connection', async (req, res) => {
  try {
    const { dbHost, dbPort, dbUser, dbPassword, dbName, webhook } = req.body;
    
    const results = {
      db: false,
      webhooks: false
    };
    
    // Test database connection
    try {
      const mysql = require('mysql2/promise');
      const connection = await mysql.createConnection({
        host: dbHost,
        port: dbPort || 3306,
        user: dbUser,
        password: dbPassword,
        database: dbName
      });
      
      await connection.execute('SELECT 1');
      await connection.end();
      results.db = true;
    } catch (dbError) {
      console.error('Database test failed:', dbError.message);
      results.db = false;
    }
    
    // Test webhook
    if (webhook) {
      try {
        const axios = require('axios');
        await axios.post(webhook, {
          content: 'EC Admin Ultimate - Test webhook from setup wizard'
        });
        results.webhooks = true;
      } catch (webhookError) {
        console.error('Webhook test failed:', webhookError.message);
        results.webhooks = false;
      }
    } else {
      results.webhooks = true; // No webhook to test
    }
    
    res.json(results);
  } catch (error) {
    console.error('Error testing connection:', error);
    res.status(500).json({ error: 'Failed to test connection' });
  }
});

// ============================================================================
// COMPLETE SETUP
// ============================================================================

router.post('/complete', async (req, res) => {
  try {
    const {
      cityName,
      framework,
      dbHost,
      dbPort,
      dbUser,
      dbPassword,
      dbName,
      ownerSteam,
      ownerLicense,
      ownerDiscord,
      webhookAdmin,
      webhookBans,
      apiBaseUrl
    } = req.body;
    
    // Generate config.lua content
    const configContent = `-- EC Admin Ultimate - Configuration
-- Auto-generated by Setup Wizard

Config = {}

-- City Information
Config.CityName = "${cityName || 'My City'}"
Config.Framework = "${framework || 'standalone'}"

-- Database Configuration
Config.Database = {
    host = "${dbHost || 'localhost'}",
    port = ${dbPort || 3306},
    user = "${dbUser || 'root'}",
    password = "${dbPassword || ''}",
    database = "${dbName || 'ec_admin'}"
}

-- Owner Identifiers
Config.Owner = {
    steam = "${ownerSteam || ''}",
    license = "${ownerLicense || ''}",
    discord = "${ownerDiscord || ''}"
}

-- Discord Webhooks
Config.DiscordWebhook = "${webhookAdmin || ''}"
Config.BanWebhook = "${webhookBans || ''}"

-- API Configuration
Config.APIBaseURL = "${apiBaseUrl || 'https://api.ecbetasolutions.com'}"

-- Admin Menu Settings
Config.MenuKey = 'F2'
Config.MenuCommand = 'adminmenu'

-- Permissions
Config.UseAcePermissions = true

return Config
`;
    
    // Write config.lua
    const configPath = path.join(__dirname, '../../../config.lua');
    await fs.writeFile(configPath, configContent, 'utf8');
    
    // Send success response
    res.json({
      success: true,
      message: 'Configuration saved successfully'
    });
    
    // Send webhook notification if provided
    if (webhookAdmin) {
      try {
        const axios = require('axios');
        await axios.post(webhookAdmin, {
          embeds: [{
            title: '✅ EC Admin Ultimate - Setup Complete',
            description: `Setup wizard completed for **${cityName}**`,
            color: 3066993,
            fields: [
              { name: 'Framework', value: framework, inline: true },
              { name: 'Database', value: dbName, inline: true }
            ],
            timestamp: new Date().toISOString()
          }]
        });
      } catch (webhookError) {
        console.error('Failed to send webhook notification:', webhookError.message);
      }
    }
  } catch (error) {
    console.error('Error completing setup:', error);
    res.status(500).json({ error: 'Failed to complete setup' });
  }
});

// ============================================================================
// CHECK IF HOST FOLDER EXISTS
// ============================================================================

router.get('/check-host', async (req, res) => {
  try {
    const hostPath = path.join(__dirname, '../../');
    let hostExists = false;
    
    try {
      const stats = await fs.stat(hostPath);
      hostExists = stats.isDirectory();
    } catch {
      hostExists = false;
    }
    
    res.json({
      hostExists: hostExists
    });
  } catch (error) {
    console.error('Error checking host folder:', error);
    res.status(500).json({ error: 'Failed to check host folder' });
  }
});

// ============================================================================
// GOOGLE OAUTH (HOST ONLY)
// ============================================================================

router.get('/oauth/google', (req, res) => {
  const clientId = process.env.GOOGLE_CLIENT_ID;
  const redirectUri = process.env.GOOGLE_REDIRECT_URI || 'http://localhost:3000/api/setup/oauth/callback';
  
  if (!clientId) {
    return res.status(500).send('Google OAuth not configured');
  }
  
  const googleAuthUrl = `https://accounts.google.com/o/oauth2/v2/auth?` +
    `client_id=${clientId}&` +
    `redirect_uri=${encodeURIComponent(redirectUri)}&` +
    `response_type=code&` +
    `scope=email%20profile&` +
    `access_type=offline&` +
    `hd=ecbetasolutions.com`; // Domain restriction
  
  res.redirect(googleAuthUrl);
});

router.get('/oauth/callback', async (req, res) => {
  try {
    const { code } = req.query;
    
    if (!code) {
      return res.redirect('/?oauth=error&message=missing_code');
    }
    
    // TODO: Exchange code for token and verify email
    // For now, just redirect back
    res.redirect('/?oauth=success');
  } catch (error) {
    console.error('OAuth callback error:', error);
    res.redirect('/?oauth=error');
  }
});

// ============================================================================
// LICENSE VALIDATION (HOST ONLY)
// ============================================================================

router.post('/validateLicense', async (req, res) => {
  try {
    const { licenseKey } = req.body;
    
    if (!licenseKey) {
      return res.status(400).json({ 
        valid: false, 
        error: 'License key is required' 
      });
    }
    
    // For development, accept any key starting with "NRG-"
    const isValid = licenseKey.startsWith('NRG-');
    
    res.json({
      valid: isValid,
      message: isValid ? 'License validated successfully' : 'Invalid license key format'
    });
  } catch (error) {
    console.error('License validation error:', error);
    res.status(500).json({ 
      valid: false, 
      error: 'Failed to validate license' 
    });
  }
});

// ============================================================================
// BUILD 20 APIs (HOST ONLY) - Server-Sent Events
// ============================================================================

router.post('/build', async (req, res) => {
  // Set headers for SSE
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('Access-Control-Allow-Origin', '*');
  
  const apis = [
    'player-management',
    'vehicle-management',
    'economy-system',
    'ban-system',
    'report-system',
    'audit-logging',
    'webhook-integration',
    'analytics-dashboard',
    'api-key-management',
    'ip-allowlist',
    'oauth-system',
    'license-validation',
    'city-management',
    'nrg-staff-tools',
    'metrics-collector',
    'backup-system',
    'notification-service',
    'rate-limiter',
    'security-monitor',
    'health-checker'
  ];
  
  // Build each API
  for (let i = 0; i < apis.length; i++) {
    const api = apis[i];
    
    // Progress update
    res.write(`data: ${JSON.stringify({
      type: 'progress',
      api: api,
      current: i + 1,
      total: apis.length,
      status: 'building'
    })}\n\n`);
    
    // Log message
    res.write(`data: ${JSON.stringify({
      type: 'log',
      message: `Building ${api}...`
    })}\n\n`);
    
    // Simulate build time (500-1500ms)
    await new Promise(resolve => setTimeout(resolve, 500 + Math.random() * 1000));
    
    // Success update
    res.write(`data: ${JSON.stringify({
      type: 'progress',
      api: api,
      current: i + 1,
      total: apis.length,
      status: 'success'
    })}\n\n`);
    
    res.write(`data: ${JSON.stringify({
      type: 'log',
      message: `✅ ${api} built successfully`
    })}\n\n`);
  }
  
  // Complete
  res.write(`data: ${JSON.stringify({
    type: 'complete',
    message: 'All 20 APIs built successfully'
  })}\n\n`);
  
  res.end();
});

module.exports = router;
